[2024-09-26 07:59:01.2114] [INFO] [D:\a\_work\1\s\src\modules\launcher\PowerLauncher\App.xaml.cs::55]
Starting PowerToys Run with PID=24264

[2024-09-26 07:59:01.2490] [INFO] [D:\a\_work\1\s\src\modules\launcher\PowerLauncher\App.xaml.cs::66]
Runner pid=26668

[2024-09-26 07:59:01.5750] [INFO] [D:\a\_work\1\s\src\modules\launcher\PowerLauncher\App.xaml.cs::108]
On Startup.

[2024-09-26 07:59:01.7332] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Stopwatch.cs::44]
ImageLoader.Initialize - Preload images cost <4ms>

[2024-09-26 07:59:01.7332] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Image\ImageLoader.cs::99]
Number of preload images is <109>, Images Number: 2, Unique Items 2

[2024-09-26 07:59:01.8091] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Stopwatch.cs::44]
|Wox.Infrastructure.Alphabet.Initialize|Preload pinyin cache <52ms>

[2024-09-26 07:59:01.8091] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Alphabet.cs::46]
Number of preload pinyin combination<0>

[2024-09-26 07:59:02.0340] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Calculator> is <8ms>

[2024-09-26 07:59:02.0507] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Folder> is <2ms>

[2024-09-26 07:59:02.0507] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <History> is <0ms>

[2024-09-26 07:59:02.0507] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Windows Indexer> is <1ms>

[2024-09-26 07:59:02.0507] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <OneNote> is <0ms>

[2024-09-26 07:59:02.0694] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <PowerToys> is <1ms>

[2024-09-26 07:59:02.4045] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Program> is <306ms>

[2024-09-26 07:59:02.4045] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Registry> is <1ms>

[2024-09-26 07:59:02.4100] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Service> is <1ms>

[2024-09-26 07:59:02.4100] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Shell> is <5ms>

[2024-09-26 07:59:02.4100] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <System Commands> is <2ms>

[2024-09-26 07:59:02.4100] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Time and date> is <0ms>

[2024-09-26 07:59:02.4397] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Unit Converter> is <0ms>

[2024-09-26 07:59:02.4615] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Windows Uri Handler> is <2ms>

[2024-09-26 07:59:02.4615] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <ValueGenerator> is <1ms>

[2024-09-26 07:59:02.5577] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <VS Code Workspaces> is <58ms>

[2024-09-26 07:59:02.5577] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Web Search> is <0ms>

[2024-09-26 07:59:02.5577] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Windows Settings> is <1ms>

[2024-09-26 07:59:02.5861] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Windows Terminal> is <21ms>

[2024-09-26 07:59:02.5861] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Window Walker> is <1ms>

[2024-09-26 07:59:03.0388] [INFO] [D:\a\_work\1\s\src\modules\launcher\PowerLauncher\SettingsReader.cs::87]
Successfully read new settings. retryCount=1

[2024-09-26 07:59:03.0388] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Storage\JsonStorage`1.cs::139]
Saving cached data at <C:\Users\LENOVO LEGION\AppData\Local\Microsoft\PowerToys\PowerToys Run\Settings\Plugins\Microsoft.Plugin.Shell\ShellPluginSettings.json>

[2024-09-26 07:59:03.0544] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <Service> is <1ms>

[2024-09-26 07:59:03.0544] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <Registry> is <1ms>

[2024-09-26 07:59:03.0544] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <History> is <0ms>

[2024-09-26 07:59:03.0544] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <Time and date> is <0ms>

[2024-09-26 07:59:03.0820] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <Folder> is <31ms>

[2024-09-26 07:59:03.0544] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <ValueGenerator> is <1ms>

[2024-09-26 07:59:03.0544] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <Unit Converter> is <0ms>

[2024-09-26 07:59:03.0544] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <Windows Uri Handler> is <2ms>

[2024-09-26 07:59:03.0544] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <Calculator> is <8ms>

[2024-09-26 07:59:03.0544] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <System Commands> is <2ms>

[2024-09-26 07:59:03.0544] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\Common\DefaultBrowserInfo.cs::74]
I've tried updating the chosen Web Browser info at least once.

[2024-09-26 07:59:03.0544] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <PowerToys> is <9ms>

[2024-09-26 07:59:03.0820] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <Window Walker> is <1ms>

[2024-09-26 07:59:03.0820] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <Windows Indexer> is <30ms>

[2024-09-26 07:59:03.0544] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <Shell> is <5ms>

[2024-09-26 07:59:03.0820] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <Web Search> is <34ms>

[2024-09-26 07:59:03.0820] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <Windows Settings> is <12ms>

[2024-09-26 07:59:04.4940] [INFO] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Storage\PackageRepository.cs::111]
Indexed 54 packaged applications

[2024-09-26 07:59:04.4940] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Stopwatch.cs::44]
Microsoft.Plugin.Program.Main - Package index cost <1300ms>

[2024-09-26 07:59:04.9971] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\ShellLinkHelper.cs::169]
-------------------------- Begin exception --------------------------
Message: Failed to fetch description for C:\Windows\syswow64\odbcad32.exe, Error HRESULT E_FAIL has been returned from a call to a COM component.

Exception full name  : System.Runtime.InteropServices.COMException
Exception message    : Error HRESULT E_FAIL has been returned from a call to a COM component.
Exception stack trace:
   at Wox.Infrastructure.ShellLinkHelper.IShellLinkW.GetDescription(StringBuilder pszName, Int32 cchMaxName)
   at Wox.Infrastructure.ShellLinkHelper.RetrieveTargetPath(String path)
Exception source     : Wox.Infrastructure
Exception target site: Void GetDescription(System.Text.StringBuilder, Int32)
Exception HResult    : -2147467259
-------------------------- End exception --------------------------


[2024-09-26 07:59:05.0424] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\ShellLinkHelper.cs::169]
-------------------------- Begin exception --------------------------
Message: Failed to fetch description for C:\PROGRA~2\WINDOW~4\wmplayer.exe, Error HRESULT E_FAIL has been returned from a call to a COM component.

Exception full name  : System.Runtime.InteropServices.COMException
Exception message    : Error HRESULT E_FAIL has been returned from a call to a COM component.
Exception stack trace:
   at Wox.Infrastructure.ShellLinkHelper.IShellLinkW.GetDescription(StringBuilder pszName, Int32 cchMaxName)
   at Wox.Infrastructure.ShellLinkHelper.RetrieveTargetPath(String path)
Exception source     : Wox.Infrastructure
Exception target site: Void GetDescription(System.Text.StringBuilder, Int32)
Exception HResult    : -2147467259
-------------------------- End exception --------------------------


[2024-09-26 07:59:11.0163] [INFO] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Storage\Win32ProgramRepository.cs::243]
Indexed 1548 win32 applications

[2024-09-26 07:59:11.0163] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Stopwatch.cs::44]
Microsoft.Plugin.Program.Main - Win32Program index cost <7822ms>

[2024-09-26 07:59:11.0163] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <Program> is <8270ms>

[2024-09-26 07:59:11.0163] [INFO] [D:\a\_work\1\s\src\modules\launcher\PowerLauncher\ViewModel\MainViewModel.cs::1333]
Refresh plugins overview

[2024-09-26 07:59:11.0163] [INFO] [D:\a\_work\1\s\src\modules\launcher\PowerLauncher\App.xaml.cs::157]
Begin PowerToys Run startup ----------------------------------------------------
Runtime info:
Version: 0.84.0.0
OS Version: Microsoft Windows NT 10.0.22631.0
IntPtr Length: 8
x64: True
End PowerToys Run startup ----------------------------------------------------  


[2024-09-26 07:59:11.0163] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Stopwatch.cs::44]
App.OnStartup - Startup cost <9445ms>

[2024-09-26 07:59:11.0163] [INFO] [D:\a\_work\1\s\src\modules\launcher\PowerLauncher\MainWindow.xaml.cs::88]
Send Run settings telemetry

[2024-09-26 07:59:11.2109] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Stopwatch.cs::44]
EnvironmentHelper.GetProtectedEnvironmentVariables - Duration cost <0ms>

[2024-09-26 07:59:11.2109] [INFO] [D:\a\_work\1\s\src\modules\launcher\PowerLauncher\ViewModel\MainViewModel.cs::100]
RegisterHotkey()

[2024-09-26 07:59:11.2109] [INFO] [D:\a\_work\1\s\src\modules\launcher\PowerLauncher\ViewModel\MainViewModel.cs::853]
Set HotKey()

[2024-09-26 07:59:11.2109] [INFO] [D:\a\_work\1\s\src\modules\launcher\PowerLauncher\ViewModel\MainViewModel.cs::894]
Registered global hotkey

[2024-09-26 08:02:41.0965] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MSTeams
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-26 08:02:41.1808] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MSTeams
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-26 08:20:43.8834] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-26 08:20:43.8834] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-26 08:20:43.8937] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-26 08:20:43.8937] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-26 08:20:43.9006] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-26 08:20:43.9006] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-26 08:20:44.1116] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-26 08:20:44.1116] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-26 08:20:44.1184] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-26 08:20:44.1184] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-26 08:20:44.1184] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-26 08:20:44.1184] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-26 08:20:44.6719] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception Microsoft.BingWeather
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-26 08:20:44.6719] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception Microsoft.BingWeather
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-26 08:20:44.6719] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception Microsoft.BingWeather
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-26 08:20:44.6719] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception Microsoft.BingWeather
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-26 08:20:44.6862] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception Microsoft.BingWeather
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-26 08:20:44.6862] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception Microsoft.BingWeather
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-26 08:20:45.1480] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception Microsoft.MicrosoftOfficeHub
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-26 08:20:45.1480] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception Microsoft.MicrosoftOfficeHub
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-26 08:20:45.1551] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception Microsoft.MicrosoftOfficeHub
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-26 08:20:45.1551] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception Microsoft.MicrosoftOfficeHub
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-26 08:20:45.1551] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception Microsoft.MicrosoftOfficeHub
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-26 08:20:45.1644] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception Microsoft.MicrosoftOfficeHub
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-26 08:20:45.5948] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Storage\PackageRepository.cs::88]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Windows.Storage.StorageFolder
		Exception thrown in called method: Microsoft.Win32.SafeHandles.SafeFileHandle CreateFile(System.String, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare, System.IO.FileOptions)
		Possible interpretation of the error: Could not find file 'C:\Program Files\WindowsApps\Microsoft.BingWeather_4.53.62621.0_neutral_~_8wekyb3d8bbwe\AppxManifest.xml'.
		Possible resolution: Not yet known

Exception full name  : System.IO.FileNotFoundException
Exception message    : Could not find file 'C:\Program Files\WindowsApps\Microsoft.BingWeather_4.53.62621.0_neutral_~_8wekyb3d8bbwe\AppxManifest.xml'.
Exception stack trace:
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy)
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   at System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
   at Microsoft.Plugin.Program.Programs.UWP.XmlNamespaces(String path)
   at Microsoft.Plugin.Program.Programs.UWP.InitializeAppInfo(String installedLocation)
   at Microsoft.Plugin.Program.Storage.PackageRepository.AddPackage(Package package)
Exception source     : System.Private.CoreLib
Exception target site: Microsoft.Win32.SafeHandles.SafeFileHandle CreateFile(System.String, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare, System.IO.FileOptions)
Exception HResult    : -2147024894
-------------------------- End exception --------------------------


[2024-09-26 08:20:46.3644] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Storage\PackageRepository.cs::88]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Windows.Storage.StorageFolder
		Exception thrown in called method: Microsoft.Win32.SafeHandles.SafeFileHandle CreateFile(System.String, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare, System.IO.FileOptions)
		Possible interpretation of the error: Could not find file 'C:\Program Files\WindowsApps\Microsoft.MicrosoftOfficeHub_18.2409.1102.0_neutral_~_8wekyb3d8bbwe\AppxManifest.xml'.
		Possible resolution: Not yet known

Exception full name  : System.IO.FileNotFoundException
Exception message    : Could not find file 'C:\Program Files\WindowsApps\Microsoft.MicrosoftOfficeHub_18.2409.1102.0_neutral_~_8wekyb3d8bbwe\AppxManifest.xml'.
Exception stack trace:
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy)
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   at System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
   at Microsoft.Plugin.Program.Programs.UWP.XmlNamespaces(String path)
   at Microsoft.Plugin.Program.Programs.UWP.InitializeAppInfo(String installedLocation)
   at Microsoft.Plugin.Program.Storage.PackageRepository.AddPackage(Package package)
Exception source     : System.Private.CoreLib
Exception target site: Microsoft.Win32.SafeHandles.SafeFileHandle CreateFile(System.String, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare, System.IO.FileOptions)
Exception HResult    : -2147024894
-------------------------- End exception --------------------------


[2024-09-26 08:20:54.6055] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception Microsoft.WindowsSoundRecorder
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-26 08:20:54.6055] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception Microsoft.WindowsSoundRecorder
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-26 08:20:54.6055] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception Microsoft.WindowsSoundRecorder
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-26 08:20:54.6055] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception Microsoft.WindowsSoundRecorder
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-26 08:20:54.6197] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception Microsoft.WindowsSoundRecorder
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-26 08:20:54.7394] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception Microsoft.PowerAutomateDesktop
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-26 08:20:54.7394] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception Microsoft.PowerAutomateDesktop
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-26 08:20:54.7394] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception Microsoft.PowerAutomateDesktop
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-26 08:20:54.7394] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception Microsoft.PowerAutomateDesktop
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-26 08:20:54.7505] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception Microsoft.PowerAutomateDesktop
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-26 08:20:54.7505] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception Microsoft.PowerAutomateDesktop
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-26 08:20:55.4681] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Storage\PackageRepository.cs::88]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Windows.Storage.StorageFolder
		Exception thrown in called method: Microsoft.Win32.SafeHandles.SafeFileHandle CreateFile(System.String, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare, System.IO.FileOptions)
		Possible interpretation of the error: Could not find file 'C:\Program Files\WindowsApps\Microsoft.WindowsSoundRecorder_2021.2408.6.0_neutral_~_8wekyb3d8bbwe\AppxManifest.xml'.
		Possible resolution: Not yet known

Exception full name  : System.IO.FileNotFoundException
Exception message    : Could not find file 'C:\Program Files\WindowsApps\Microsoft.WindowsSoundRecorder_2021.2408.6.0_neutral_~_8wekyb3d8bbwe\AppxManifest.xml'.
Exception stack trace:
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy)
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   at System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
   at Microsoft.Plugin.Program.Programs.UWP.XmlNamespaces(String path)
   at Microsoft.Plugin.Program.Programs.UWP.InitializeAppInfo(String installedLocation)
   at Microsoft.Plugin.Program.Storage.PackageRepository.AddPackage(Package package)
Exception source     : System.Private.CoreLib
Exception target site: Microsoft.Win32.SafeHandles.SafeFileHandle CreateFile(System.String, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare, System.IO.FileOptions)
Exception HResult    : -2147024894
-------------------------- End exception --------------------------


[2024-09-26 08:20:55.6770] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Storage\PackageRepository.cs::88]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Windows.Storage.StorageFolder
		Exception thrown in called method: Microsoft.Win32.SafeHandles.SafeFileHandle CreateFile(System.String, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare, System.IO.FileOptions)
		Possible interpretation of the error: Could not find file 'C:\Program Files\WindowsApps\Microsoft.PowerAutomateDesktop_11.2409.203.0_neutral_~_8wekyb3d8bbwe\AppxManifest.xml'.
		Possible resolution: Not yet known

Exception full name  : System.IO.FileNotFoundException
Exception message    : Could not find file 'C:\Program Files\WindowsApps\Microsoft.PowerAutomateDesktop_11.2409.203.0_neutral_~_8wekyb3d8bbwe\AppxManifest.xml'.
Exception stack trace:
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy)
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   at System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
   at Microsoft.Plugin.Program.Programs.UWP.XmlNamespaces(String path)
   at Microsoft.Plugin.Program.Programs.UWP.InitializeAppInfo(String installedLocation)
   at Microsoft.Plugin.Program.Storage.PackageRepository.AddPackage(Package package)
Exception source     : System.Private.CoreLib
Exception target site: Microsoft.Win32.SafeHandles.SafeFileHandle CreateFile(System.String, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare, System.IO.FileOptions)
Exception HResult    : -2147024894
-------------------------- End exception --------------------------


[2024-09-26 08:20:59.7077] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception Microsoft.ZuneMusic
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-26 08:20:59.7077] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception Microsoft.ZuneMusic
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-26 08:20:59.7077] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception Microsoft.ZuneMusic
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-26 08:20:59.7077] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception Microsoft.ZuneMusic
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-26 08:20:59.7077] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception Microsoft.ZuneMusic
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-26 08:20:59.7212] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception Microsoft.ZuneMusic
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-26 08:21:02.2760] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Storage\PackageRepository.cs::88]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Windows.Storage.StorageFolder
		Exception thrown in called method: Microsoft.Win32.SafeHandles.SafeFileHandle CreateFile(System.String, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare, System.IO.FileOptions)
		Possible interpretation of the error: Could not find file 'C:\Program Files\WindowsApps\Microsoft.ZuneMusic_11.2408.4.0_neutral_~_8wekyb3d8bbwe\AppxManifest.xml'.
		Possible resolution: Not yet known

Exception full name  : System.IO.FileNotFoundException
Exception message    : Could not find file 'C:\Program Files\WindowsApps\Microsoft.ZuneMusic_11.2408.4.0_neutral_~_8wekyb3d8bbwe\AppxManifest.xml'.
Exception stack trace:
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy)
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   at System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
   at Microsoft.Plugin.Program.Programs.UWP.XmlNamespaces(String path)
   at Microsoft.Plugin.Program.Programs.UWP.InitializeAppInfo(String installedLocation)
   at Microsoft.Plugin.Program.Storage.PackageRepository.AddPackage(Package package)
Exception source     : System.Private.CoreLib
Exception target site: Microsoft.Win32.SafeHandles.SafeFileHandle CreateFile(System.String, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare, System.IO.FileOptions)
Exception HResult    : -2147024894
-------------------------- End exception --------------------------


[2024-09-26 08:21:05.5304] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception Microsoft.LanguageExperiencePackvi-VN
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-26 08:21:06.1915] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception Microsoft.WindowsCamera
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-26 08:21:06.1915] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception Microsoft.WindowsCamera
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-26 08:21:06.1975] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception Microsoft.WindowsCamera
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-26 08:21:06.1975] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception Microsoft.WindowsCamera
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-26 08:21:06.1975] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception Microsoft.WindowsCamera
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-26 08:21:06.1975] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception Microsoft.WindowsCamera
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-26 08:21:06.8612] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Storage\PackageRepository.cs::88]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Windows.Storage.StorageFolder
		Exception thrown in called method: Microsoft.Win32.SafeHandles.SafeFileHandle CreateFile(System.String, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare, System.IO.FileOptions)
		Possible interpretation of the error: Could not find file 'C:\Program Files\WindowsApps\Microsoft.WindowsCamera_2022.2408.1.0_neutral_~_8wekyb3d8bbwe\AppxManifest.xml'.
		Possible resolution: Not yet known

Exception full name  : System.IO.FileNotFoundException
Exception message    : Could not find file 'C:\Program Files\WindowsApps\Microsoft.WindowsCamera_2022.2408.1.0_neutral_~_8wekyb3d8bbwe\AppxManifest.xml'.
Exception stack trace:
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
   at System.Xml.XmlTextReaderImpl..ctor(String uriStr, XmlReaderSettings settings, XmlParserContext context, XmlResolver uriResolver)
   at System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
   at Microsoft.Plugin.Program.Programs.UWP.XmlNamespaces(String path)
   at Microsoft.Plugin.Program.Programs.UWP.InitializeAppInfo(String installedLocation)
   at Microsoft.Plugin.Program.Storage.PackageRepository.AddPackage(Package package)
Exception source     : System.Private.CoreLib
Exception target site: Microsoft.Win32.SafeHandles.SafeFileHandle CreateFile(System.String, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare, System.IO.FileOptions)
Exception HResult    : -2147024894
-------------------------- End exception --------------------------


[2024-09-26 08:26:05.5934] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-26 08:26:05.5934] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-26 08:26:05.5934] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-26 08:26:05.5934] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-26 08:26:05.6048] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-26 08:26:05.6048] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-26 08:26:05.6937] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-26 08:26:05.6956] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-26 08:26:05.6956] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-26 08:26:05.6956] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-26 08:26:05.6956] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-26 08:26:05.6956] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-26 08:58:30.6965] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MSTeams
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-26 11:13:22.3019] [INFO] [D:\a\_work\1\s\src\modules\launcher\PowerLauncher\App.xaml.cs::206]
Application.Current.SessionEnding

[2024-09-26 11:13:22.3532] [INFO] [D:\a\_work\1\s\src\modules\launcher\PowerLauncher\App.xaml.cs::254]
Start PowerToys Run Exit----------------------------------------------------  

[2024-09-26 11:13:22.3701] [INFO] [D:\a\_work\1\s\src\modules\launcher\PowerLauncher\App.xaml.cs::97]
Runner with pid=26668 exited. Exiting PowerToys Run

[2024-09-26 11:13:22.4160] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Storage\JsonStorage`1.cs::139]
Saving cached data at <C:\Users\LENOVO LEGION\AppData\Local\Microsoft\PowerToys\PowerToys Run\Settings\QueryHistory.json>

[2024-09-26 11:13:22.4295] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Storage\JsonStorage`1.cs::139]
Saving cached data at <C:\Users\LENOVO LEGION\AppData\Local\Microsoft\PowerToys\PowerToys Run\Settings\UserSelectedRecord.json>

[2024-09-26 11:13:22.4595] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Storage\JsonStorage`1.cs::139]
Saving cached data at <C:\Users\LENOVO LEGION\AppData\Local\Microsoft\PowerToys\PowerToys Run\Settings\PowerToysRunSettings.json>

[2024-09-26 11:13:22.4660] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Storage\JsonStorage`1.cs::139]
Saving cached data at <C:\Users\LENOVO LEGION\AppData\Local\Microsoft\PowerToys\PowerToys Run\Settings\Plugins\Microsoft.Plugin.Folder\FolderSettings.json>

[2024-09-26 11:13:22.4660] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Storage\JsonStorage`1.cs::139]
Saving cached data at <C:\Users\LENOVO LEGION\AppData\Local\Microsoft\PowerToys\PowerToys Run\Settings\Plugins\Microsoft.Plugin.Indexer\IndexerSettings.json>

[2024-09-26 11:13:22.4660] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Storage\JsonStorage`1.cs::139]
Saving cached data at <C:\Users\LENOVO LEGION\AppData\Local\Microsoft\PowerToys\PowerToys Run\Settings\Plugins\Microsoft.Plugin.Program\ProgramPluginSettings.json>

[2024-09-26 11:13:22.4660] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Storage\JsonStorage`1.cs::139]
Saving cached data at <C:\Users\LENOVO LEGION\AppData\Local\Microsoft\PowerToys\PowerToys Run\Settings\Plugins\Microsoft.Plugin.Shell\ShellPluginSettings.json>

[2024-09-26 11:13:22.4836] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Storage\JsonStorage`1.cs::139]
Saving cached data at <C:\Users\LENOVO LEGION\AppData\Local\Microsoft\PowerToys\PowerToys Run\Settings\Plugins\Microsoft.Plugin.Uri\UriSettings.json>

[2024-09-26 11:13:22.5068] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Storage\JsonStorage`1.cs::139]
Saving cached data at <C:\Users\LENOVO LEGION\AppData\Local\Microsoft\PowerToys\PowerToys Run\Settings\ImageCache.json>

[2024-09-26 11:13:22.5215] [INFO] [D:\a\_work\1\s\src\modules\launcher\PowerLauncher\App.xaml.cs::265]
End PowerToys Run Exit ----------------------------------------------------  

[2024-09-26 11:13:22.5215] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Stopwatch.cs::44]
App.OnExit - Exit cost <169ms>

[2024-09-26 12:38:03.8097] [INFO] [D:\a\_work\1\s\src\modules\launcher\PowerLauncher\App.xaml.cs::55]
Starting PowerToys Run with PID=9968

[2024-09-26 12:38:03.8281] [INFO] [D:\a\_work\1\s\src\modules\launcher\PowerLauncher\App.xaml.cs::66]
Runner pid=24160

[2024-09-26 12:38:04.1283] [INFO] [D:\a\_work\1\s\src\modules\launcher\PowerLauncher\App.xaml.cs::108]
On Startup.

[2024-09-26 12:38:04.2892] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Stopwatch.cs::44]
ImageLoader.Initialize - Preload images cost <4ms>

[2024-09-26 12:38:04.2892] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Image\ImageLoader.cs::99]
Number of preload images is <109>, Images Number: 2, Unique Items 2

[2024-09-26 12:38:04.3950] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Stopwatch.cs::44]
|Wox.Infrastructure.Alphabet.Initialize|Preload pinyin cache <81ms>

[2024-09-26 12:38:04.3950] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Alphabet.cs::46]
Number of preload pinyin combination<0>

[2024-09-26 12:38:04.6026] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Calculator> is <4ms>

[2024-09-26 12:38:04.6422] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Folder> is <2ms>

[2024-09-26 12:38:04.6422] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <History> is <0ms>

[2024-09-26 12:38:04.6621] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Windows Indexer> is <1ms>

[2024-09-26 12:38:04.6818] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <OneNote> is <0ms>

[2024-09-26 12:38:04.6818] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <PowerToys> is <1ms>

[2024-09-26 12:38:05.2114] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Program> is <525ms>

[2024-09-26 12:38:05.2114] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Registry> is <1ms>

[2024-09-26 12:38:05.2114] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Service> is <2ms>

[2024-09-26 12:38:05.2114] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Shell> is <5ms>

[2024-09-26 12:38:05.2114] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <System Commands> is <1ms>

[2024-09-26 12:38:05.2418] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Time and date> is <0ms>

[2024-09-26 12:38:05.2418] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Unit Converter> is <0ms>

[2024-09-26 12:38:05.2418] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Windows Uri Handler> is <2ms>

[2024-09-26 12:38:05.2418] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <ValueGenerator> is <0ms>

[2024-09-26 12:38:05.2857] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <VS Code Workspaces> is <34ms>

[2024-09-26 12:38:05.2857] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Web Search> is <0ms>

[2024-09-26 12:38:05.2857] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Windows Settings> is <0ms>

[2024-09-26 12:38:05.3318] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Windows Terminal> is <40ms>

[2024-09-26 12:38:05.3318] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Window Walker> is <0ms>

[2024-09-26 12:38:05.6977] [INFO] [D:\a\_work\1\s\src\modules\launcher\PowerLauncher\SettingsReader.cs::87]
Successfully read new settings. retryCount=1

[2024-09-26 12:38:05.7163] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Storage\JsonStorage`1.cs::139]
Saving cached data at <C:\Users\LENOVO LEGION\AppData\Local\Microsoft\PowerToys\PowerToys Run\Settings\Plugins\Microsoft.Plugin.Shell\ShellPluginSettings.json>

[2024-09-26 12:38:05.7163] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <Time and date> is <0ms>

[2024-09-26 12:38:05.7163] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <Service> is <2ms>

[2024-09-26 12:38:05.7163] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <Shell> is <5ms>

[2024-09-26 12:38:05.7163] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <Registry> is <1ms>

[2024-09-26 12:38:05.7163] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <ValueGenerator> is <0ms>

[2024-09-26 12:38:05.7163] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <Web Search> is <0ms>

[2024-09-26 12:38:05.7163] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <History> is <0ms>

[2024-09-26 12:38:05.7163] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <Unit Converter> is <0ms>

[2024-09-26 12:38:05.7163] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <Calculator> is <4ms>

[2024-09-26 12:38:05.7163] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <System Commands> is <1ms>

[2024-09-26 12:38:05.7163] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\Common\DefaultBrowserInfo.cs::74]
I've tried updating the chosen Web Browser info at least once.

[2024-09-26 12:38:05.7163] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <Window Walker> is <0ms>

[2024-09-26 12:38:05.7163] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <Folder> is <4ms>

[2024-09-26 12:38:05.7163] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <Windows Indexer> is <3ms>

[2024-09-26 12:38:05.7163] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <Windows Uri Handler> is <7ms>

[2024-09-26 12:38:05.7326] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <PowerToys> is <9ms>

[2024-09-26 12:38:05.7326] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <Windows Settings> is <9ms>

[2024-09-26 12:38:07.1173] [INFO] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Storage\PackageRepository.cs::111]
Indexed 54 packaged applications

[2024-09-26 12:38:07.1173] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Stopwatch.cs::44]
Microsoft.Plugin.Program.Main - Package index cost <1252ms>

[2024-09-26 12:38:07.7346] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\ShellLinkHelper.cs::169]
-------------------------- Begin exception --------------------------
Message: Failed to fetch description for C:\Windows\syswow64\odbcad32.exe, Error HRESULT E_FAIL has been returned from a call to a COM component.

Exception full name  : System.Runtime.InteropServices.COMException
Exception message    : Error HRESULT E_FAIL has been returned from a call to a COM component.
Exception stack trace:
   at Wox.Infrastructure.ShellLinkHelper.IShellLinkW.GetDescription(StringBuilder pszName, Int32 cchMaxName)
   at Wox.Infrastructure.ShellLinkHelper.RetrieveTargetPath(String path)
Exception source     : Wox.Infrastructure
Exception target site: Void GetDescription(System.Text.StringBuilder, Int32)
Exception HResult    : -2147467259
-------------------------- End exception --------------------------


[2024-09-26 12:38:07.7346] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\ShellLinkHelper.cs::169]
-------------------------- Begin exception --------------------------
Message: Failed to fetch description for C:\PROGRA~2\WINDOW~4\wmplayer.exe, Error HRESULT E_FAIL has been returned from a call to a COM component.

Exception full name  : System.Runtime.InteropServices.COMException
Exception message    : Error HRESULT E_FAIL has been returned from a call to a COM component.
Exception stack trace:
   at Wox.Infrastructure.ShellLinkHelper.IShellLinkW.GetDescription(StringBuilder pszName, Int32 cchMaxName)
   at Wox.Infrastructure.ShellLinkHelper.RetrieveTargetPath(String path)
Exception source     : Wox.Infrastructure
Exception target site: Void GetDescription(System.Text.StringBuilder, Int32)
Exception HResult    : -2147467259
-------------------------- End exception --------------------------


[2024-09-26 12:38:13.8759] [INFO] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Storage\Win32ProgramRepository.cs::243]
Indexed 1548 win32 applications

[2024-09-26 12:38:13.8759] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Stopwatch.cs::44]
Microsoft.Plugin.Program.Main - Win32Program index cost <8010ms>

[2024-09-26 12:38:13.8759] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <Program> is <8678ms>

[2024-09-26 12:38:13.9072] [INFO] [D:\a\_work\1\s\src\modules\launcher\PowerLauncher\ViewModel\MainViewModel.cs::1333]
Refresh plugins overview

[2024-09-26 12:38:13.9072] [INFO] [D:\a\_work\1\s\src\modules\launcher\PowerLauncher\App.xaml.cs::157]
Begin PowerToys Run startup ----------------------------------------------------
Runtime info:
Version: 0.84.0.0
OS Version: Microsoft Windows NT 10.0.22631.0
IntPtr Length: 8
x64: True
End PowerToys Run startup ----------------------------------------------------  


[2024-09-26 12:38:13.9072] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Stopwatch.cs::44]
App.OnStartup - Startup cost <9762ms>

[2024-09-26 12:38:14.2245] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Stopwatch.cs::44]
EnvironmentHelper.GetProtectedEnvironmentVariables - Duration cost <0ms>

[2024-09-26 12:38:14.2245] [INFO] [D:\a\_work\1\s\src\modules\launcher\PowerLauncher\ViewModel\MainViewModel.cs::100]
RegisterHotkey()

[2024-09-26 12:38:14.2245] [INFO] [D:\a\_work\1\s\src\modules\launcher\PowerLauncher\ViewModel\MainViewModel.cs::853]
Set HotKey()

[2024-09-26 12:38:14.2245] [INFO] [D:\a\_work\1\s\src\modules\launcher\PowerLauncher\ViewModel\MainViewModel.cs::894]
Registered global hotkey

[2024-09-26 14:15:14.4876] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception Microsoft.OutlookForWindows
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-26 15:50:12.3344] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Storage\ListRepository`1.cs::54]
Item Already Exists <ImageMagick (color depth=q16) (Ubuntu).lnk>

[2024-09-26 15:50:18.3474] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Storage\ListRepository`1.cs::54]
Item Already Exists <Install RELEASE (Ubuntu).lnk>

[2024-09-26 15:50:24.3755] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Storage\ListRepository`1.cs::54]
Item Already Exists <Tilix (Ubuntu).lnk>

[2024-09-26 15:50:30.3905] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Storage\ListRepository`1.cs::54]
Item Already Exists <xpdf (Ubuntu).lnk>

[2024-09-26 19:37:09.0470] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Storage\ListRepository`1.cs::62]
Item Not Found <Opera Browser.lnk>

[2024-09-26 19:37:16.6839] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Storage\ListRepository`1.cs::54]
Item Already Exists <Opera Browser.lnk>

[2024-09-26 23:00:33.0805] [INFO] [D:\a\_work\1\s\src\modules\launcher\PowerLauncher\App.xaml.cs::206]
Application.Current.SessionEnding

[2024-09-26 23:00:33.0866] [INFO] [D:\a\_work\1\s\src\modules\launcher\PowerLauncher\App.xaml.cs::254]
Start PowerToys Run Exit----------------------------------------------------  

[2024-09-26 23:00:33.1495] [INFO] [D:\a\_work\1\s\src\modules\launcher\PowerLauncher\App.xaml.cs::97]
Runner with pid=24160 exited. Exiting PowerToys Run

[2024-09-26 23:00:33.1888] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Storage\JsonStorage`1.cs::139]
Saving cached data at <C:\Users\LENOVO LEGION\AppData\Local\Microsoft\PowerToys\PowerToys Run\Settings\QueryHistory.json>

[2024-09-26 23:00:33.2031] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Storage\JsonStorage`1.cs::139]
Saving cached data at <C:\Users\LENOVO LEGION\AppData\Local\Microsoft\PowerToys\PowerToys Run\Settings\UserSelectedRecord.json>

[2024-09-26 23:00:33.2266] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Storage\JsonStorage`1.cs::139]
Saving cached data at <C:\Users\LENOVO LEGION\AppData\Local\Microsoft\PowerToys\PowerToys Run\Settings\PowerToysRunSettings.json>

[2024-09-26 23:00:33.2266] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Storage\JsonStorage`1.cs::139]
Saving cached data at <C:\Users\LENOVO LEGION\AppData\Local\Microsoft\PowerToys\PowerToys Run\Settings\Plugins\Microsoft.Plugin.Folder\FolderSettings.json>

[2024-09-26 23:00:33.2379] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Storage\JsonStorage`1.cs::139]
Saving cached data at <C:\Users\LENOVO LEGION\AppData\Local\Microsoft\PowerToys\PowerToys Run\Settings\Plugins\Microsoft.Plugin.Indexer\IndexerSettings.json>

[2024-09-26 23:00:33.2630] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Storage\JsonStorage`1.cs::139]
Saving cached data at <C:\Users\LENOVO LEGION\AppData\Local\Microsoft\PowerToys\PowerToys Run\Settings\Plugins\Microsoft.Plugin.Program\ProgramPluginSettings.json>

[2024-09-26 23:00:33.2669] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Storage\JsonStorage`1.cs::139]
Saving cached data at <C:\Users\LENOVO LEGION\AppData\Local\Microsoft\PowerToys\PowerToys Run\Settings\Plugins\Microsoft.Plugin.Shell\ShellPluginSettings.json>

[2024-09-26 23:00:33.2669] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Storage\JsonStorage`1.cs::139]
Saving cached data at <C:\Users\LENOVO LEGION\AppData\Local\Microsoft\PowerToys\PowerToys Run\Settings\Plugins\Microsoft.Plugin.Uri\UriSettings.json>

[2024-09-26 23:00:33.2921] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Storage\JsonStorage`1.cs::139]
Saving cached data at <C:\Users\LENOVO LEGION\AppData\Local\Microsoft\PowerToys\PowerToys Run\Settings\ImageCache.json>

[2024-09-26 23:00:33.3080] [INFO] [D:\a\_work\1\s\src\modules\launcher\PowerLauncher\App.xaml.cs::265]
End PowerToys Run Exit ----------------------------------------------------  

[2024-09-26 23:00:33.3080] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Stopwatch.cs::44]
App.OnExit - Exit cost <223ms>

